<?php $this->headTitle('Academics'); ?>
<div class="container">    
    <div class="row">
        <div class="col-md-9">
            <h1>Overview</h1>
            <p>
                
            </p>
        </div>
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Our Academic Program</h3>
                </div>
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li>Overview</li>
                        <li>Students</li>                        
                        <li>Prospectus</li>                        
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>