<div class="row">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('dashboard') ?>"> <?php echo $this->layout()->application_name; ?> </a>
        </div>
        <div class="navbar-collapse collapse navbar-inverse-collapse">
            <?php
//                            echo $this->navigation('navigation')
//                                    ->menu()
//                                    ->setUlClass('nav navbar-nav')
//                                    ->setPartial('template/navigation');
            ?>
        </div>
    </nav>
</div>
<div class="row">
    <?php // echo $this->navigation()->breadcrumbs()->setPartial('template/breadcrumbs'); ?>
</div>