<?php $this->headTitle('Our Premises'); ?>
<div class="container">    
    <div class="row">
        <div class="col-md-9">
            <h1>Overview</h1>
            <p>
                
            </p>
        </div>
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Our Premises</h3>
                </div>
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li class="active"><a href="<?=$this->url('resources/premises');?>">Overview</a></li>
                        <li><a href="<?=$this->url('resources/premises/offices');?>">Our Offices</a></li>
                        <li><a href="<?=$this->url('resources/premises/facilities');?>">Our Facilities</a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>